// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "targetLang": string;
      "sourceLang": string;
      "translate.timeout": number;
      "translate.chunkMaxChars": number;
      "translate.autoOnSelect": boolean;
      "translate.autoDebounceMs": number;
      "translate.contextAware": boolean;
      "cacheEnabled": boolean;
      "historyCapacity": number;
      "mymemory.enabled": boolean;
      "bing.enabled": boolean;
      "bing.mode": string;
      "bing.azureKey": string;
      "bing.azureRegion": string;
      "deepseek.enabled": boolean;
      "deepseek.apiKey": string;
      "deepseek.baseURL": string;
      "deepseek.model": string;
      "deepseek.prompt": string;
      "channelsOrder": string;
      "customChannels": string;
      "shortcut.translate": string;
      "shortcut.summary": string;
      "summary.model": string;
      "summary.prompt": string;
      "formatter.mergeLineBreaks": boolean;
      "formatter.fixHyphenation": boolean;
      "formatter.normalizeQuotes": boolean;
      "formatter.normalizeDashes": boolean;
      "formatter.normalizeWidth": boolean;
      "formatter.collapseWhitespace": boolean;
      "formatter.normalizeSymbols": boolean;
    };
  }
}
