// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "targetLang": string;
      "sourceLang": string;
      "translate.timeout": number;
      "translate.chunkMaxChars": number;
      "translate.autoOnSelect": boolean;
      "translate.autoDebounceMs": number;
      "translate.contextAware": boolean;
      "cacheEnabled": boolean;
      "historyCapacity": number;
      "mymemory.enabled": boolean;
      "youdao.enabled": boolean;
      "transmart.enabled": boolean;
      "volcengine.enabled": boolean;
      "google.enabled": boolean;
      "bing.enabled": boolean;
      "bing.mode": string;
      "bing.azureKey": string;
      "bing.azureRegion": string;
      "deepseek.enabled": boolean;
      "deepseek.apiKey": string;
      "deepseek.baseURL": string;
      "deepseek.model": string;
      "tencent.enabled": boolean;
      "tencent.secretId": string;
      "tencent.secretKey": string;
      "tencent.region": string;
      "baidu.enabled": boolean;
      "baidu.appId": string;
      "baidu.appKey": string;
      "baidu.action": string;
      "aliyun.enabled": boolean;
      "aliyun.accessKeyId": string;
      "aliyun.accessKeySecret": string;
      "aliyun.endpoint": string;
      "aliyun.action": string;
      "aliyun.scene": string;
      "qwenmt.enabled": boolean;
      "qwenmt.apiKey": string;
      "qwenmt.baseURL": string;
      "qwenmt.model": string;
      "qwenmt.domains": string;
      "deepseek.prompt": string;
      "channelsOrder": string;
      "customChannels": string;
      "shortcut.translate": string;
      "shortcut.summary": string;
      "summary.lang": string;
      "summary.model": string;
      "summary.prompt": string;
      "display.markdown": boolean;
      "formatter.mergeLineBreaks": boolean;
      "formatter.fixHyphenation": boolean;
      "formatter.normalizeQuotes": boolean;
      "formatter.normalizeDashes": boolean;
      "formatter.normalizeWidth": boolean;
      "formatter.collapseWhitespace": boolean;
      "formatter.normalizeSymbols": boolean;
    };
  }
}
